load("@rules_python//python:pip.bzl", "compile_pip_requirements")
load("@rules_python//python:py_binary.bzl", "py_binary")
load("@rules_python//python:py_library.bzl", "py_library")
load("@rules_python//python:py_test.bzl", "py_test")

py_library(
    name = "transform_module_bazel",
    srcs = ["transform_module_bazel.py"],
)

py_test(
    name = "transform_module_bazel_test",
    srcs = ["transform_module_bazel_test.py"],
    deps = [":transform_module_bazel"],
)

py_library(
    name = "transform_extensions_bzl",
    srcs = ["transform_extensions_bzl.py"],
)

py_test(
    name = "transform_extensions_bzl_test",
    srcs = ["transform_extensions_bzl_test.py"],
    deps = [":transform_extensions_bzl"],
)

py_binary(
    name = "validate_patches",
    srcs = ["validate_patches.py"],
)

py_test(
    name = "validate_patches_test",
    srcs = ["validate_patches_test.py"],
    deps = [":validate_patches"],
)

py_test(
    name = "validate_patches_repo_test",
    srcs = ["validate_patches_repo_test.py"],
    data = ["//versions"],
    deps = [":validate_patches"],
)

py_binary(
    name = "build",
    srcs = ["build.py"],
    deps = [
        ":transform_extensions_bzl",
        ":transform_module_bazel",
        "@llvm_project_redist_pip//zstandard",
    ],
)

py_test(
    name = "build_test",
    srcs = ["build_test.py"],
    deps = [":build"],
)

py_library(
    name = "presubmit_logic",
    srcs = ["presubmit_logic.py"],
)

py_binary(
    name = "run_presubmit",
    srcs = ["run_presubmit.py"],
    deps = [
        ":presubmit_logic",
        "@llvm_project_redist_pip//pyyaml",
        "@llvm_project_redist_pip//requests",
    ],
)

py_test(
    name = "run_presubmit_test",
    srcs = ["run_presubmit_test.py"],
    deps = [
        ":presubmit_logic",
        ":run_presubmit",
    ],
)

py_binary(
    name = "setup_presubmit",
    srcs = ["setup_presubmit.py"],
    deps = [
        ":build",
        ":presubmit_logic",
        "@llvm_project_redist_pip//pyyaml",
    ],
)

py_binary(
    name = "release_notes",
    srcs = ["release_notes.py"],
)

py_binary(
    name = "render_presubmit",
    srcs = ["render_presubmit.py"],
    deps = [
        "@llvm_project_redist_pip//pyyaml",
    ],
)

py_test(
    name = "render_presubmit_test",
    srcs = ["render_presubmit_test.py"],
    deps = [":render_presubmit"],
)

py_binary(
    name = "cherry_pick",
    srcs = ["cherry_pick.py"],
    deps = [":build"],
)

py_test(
    name = "cherry_pick_test",
    srcs = ["cherry_pick_test.py"],
    deps = [":cherry_pick"],
)

compile_pip_requirements(
    name = "requirements",
    src = "requirements.in",
    requirements_txt = "requirements.txt",
    tags = ["manual"],
)
